### ISSUE TITLE
Hive crashing while fetching queue information

### ISSUE THREAD

**Issue by Asimk21** [bbc/hive-runner-ios#14]
lib/hive/controller/ios.rb:140:in `[]': no implicit conversion of String into Integer (TypeError)
        from /Users/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-ios-0ba155529f15/lib/hive/controller/ios.rb:140:in `find_or_create_queue'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-ios-0ba155529f15/lib/hive/controller/ios.rb:126:in `block in populate_queues'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-ios-0ba155529f15/lib/hive/controller/ios.rb:126:in `map'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-ios-0ba155529f15/lib/hive/controller/ios.rb:126:in `populate_queues'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-ios-0ba155529f15/lib/hive/controller/ios.rb:38:in `block in detect'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-ios-0ba155529f15/lib/hive/controller/ios.rb:26:in `each'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-ios-0ba155529f15/lib/hive/controller/ios.rb:26:in `detect'
        from /Users/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.5/lib/hive/register.rb:60:in `block in check_controllers'
        from /Users/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.5/lib/hive/register.rb:55:in `each'
        from /Users/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.5/lib/hive/register.rb:55:in `check_controllers'
        from /Users/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.5/lib/hive/register.rb:47:in `block in run'
        from /Users/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.5/lib/hive/register.rb:44:in `loop'
        from /Users/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.5/lib/hive/register.rb:44:in `run'
        from /Users/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.5/bin/start_hive:120:in `<top (required)>'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bin/start_hive:23:in `load'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bin/start_hive:23:in `<main>'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/hive/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jonpwilson** [comment]
Should be fixed in PR #17

**Comment by jonpwilson** [comment]
Fixed as hive-runner-ios no longer requires either DeviceDB or Hive Mind for queues
